export {default as Login} from './login'
export {default as Register} from './register'
export {default as ProtectedAdmin} from './protectedAdmin'
export {default as ProtectedRoute} from './protectedRoute'
export {default as ProtectedLogin} from './protectedLogin'